# ============================
# Stage 1: Build the JAR
# ============================
FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /app

# Copy pom.xml aur dependencies download karo
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copy source aur build karo
COPY src ./src
RUN mvn clean package -DskipTests

# ============================
# Stage 2: Run the JAR
# ============================
FROM eclipse-temurin:21-jre
WORKDIR /app

# Builder se jar copy karo
COPY --from=builder /app/target/*.jar app.jar

ENV SPRING_PROFILES_ACTIVE=prod
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
